#!/usr/bin/env bash
#Creates the file /var/run/myscript.pid containing its PID
#Displays To infinity and beyond indefinitely
#Displays I hate the kill command when receiving a SIGTERM signal
#Displays Y U no love me?! when receiving a SIGINT signal
#Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

sigterm_handler() {
    echo "I hate the kill command"
    rm -f /var/run/myscript.pid
    exit 0
}

sigint_handler() {
    echo "Y U no love me?!"
}

sigquit_handler() {
    echo "Deleting PID file and terminating script"
    rm -f /var/run/myscript.pid
    exit 0
}

trap 'sigterm_handler' SIGTERM
trap 'sigint_handler' SIGINT
trap 'sigquit_handler' SIGQUIT

echo $$ > /var/run/myscript.pid

while true
do
    echo "To infinity and beyond"
    sleep 2
done
