#!/usr/bin/env bash
# A script that displays To infinity and beyond indefinitely with a sleep 2 in between each iteration
# and outputsI am invincible!!! when receiving a SIGTERM signal

sigterm_handler() {
    echo "I am invincible!!!"
}

trap 'sigterm_handler' SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
