#!/usr/bin/env bash
#script that continuously writes "I am alive!" to /tmp/my_process with a
#2-second pause between "I am alive" messages

while true
do
    echo "I am alive!" >> /tmp/my_process
    sleep 2
done
