#!/usr/bin/env bash
# A Bash script that dsplays Best school 10 times but for the 9th iteration dsplays
#Best School then Hi
i=1
while ((i<=10))
do	
	if [ $i -eq 9 ]
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	((i++))
done
